import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import { Navbar, Footer, Loader } from "@/imports";
import { Suspense } from "react";
import MaintenanceBanner from "@/components/MaintenanceBanner";
import { ToastContainer } from "react-toastify";
import { AuthInitializer } from "@/components/AuthInitializer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sanjay App",
  description: "Generated by sanjay choudhary",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <MaintenanceBanner />
        <Navbar />
        <Suspense fallback={<Loader />}>
          <AuthInitializer />
          {children}
          <ToastContainer />
        </Suspense>
        <Footer />
      </body>
    </html>
  );
}